#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

Course.all.each do |c|
  mj = MailingJob.new(c.id, Forem::SubscriptionMailer.to_s)
  mj.perform
end
