require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PendingActionsController do

  # This should return the minimal set of attributes required to create a valid
  # PendingAction. As you add validations to PendingAction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PendingActionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pending_actions as @pending_actions" do
      pending_action = PendingAction.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pending_actions).should eq([pending_action])
    end
  end

  describe "GET show" do
    it "assigns the requested pending_action as @pending_action" do
      pending_action = PendingAction.create! valid_attributes
      get :show, {:id => pending_action.to_param}, valid_session
      assigns(:pending_action).should eq(pending_action)
    end
  end

  describe "GET new" do
    it "assigns a new pending_action as @pending_action" do
      get :new, {}, valid_session
      assigns(:pending_action).should be_a_new(PendingAction)
    end
  end

  describe "GET edit" do
    it "assigns the requested pending_action as @pending_action" do
      pending_action = PendingAction.create! valid_attributes
      get :edit, {:id => pending_action.to_param}, valid_session
      assigns(:pending_action).should eq(pending_action)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PendingAction" do
        expect {
          post :create, {:pending_action => valid_attributes}, valid_session
        }.to change(PendingAction, :count).by(1)
      end

      it "assigns a newly created pending_action as @pending_action" do
        post :create, {:pending_action => valid_attributes}, valid_session
        assigns(:pending_action).should be_a(PendingAction)
        assigns(:pending_action).should be_persisted
      end

      it "redirects to the created pending_action" do
        post :create, {:pending_action => valid_attributes}, valid_session
        response.should redirect_to(PendingAction.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pending_action as @pending_action" do
        # Trigger the behavior that occurs when invalid params are submitted
        PendingAction.any_instance.stub(:save).and_return(false)
        post :create, {:pending_action => {  }}, valid_session
        assigns(:pending_action).should be_a_new(PendingAction)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PendingAction.any_instance.stub(:save).and_return(false)
        post :create, {:pending_action => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pending_action" do
        pending_action = PendingAction.create! valid_attributes
        # Assuming there are no other pending_actions in the database, this
        # specifies that the PendingAction created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PendingAction.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => pending_action.to_param, :pending_action => { "these" => "params" }}, valid_session
      end

      it "assigns the requested pending_action as @pending_action" do
        pending_action = PendingAction.create! valid_attributes
        put :update, {:id => pending_action.to_param, :pending_action => valid_attributes}, valid_session
        assigns(:pending_action).should eq(pending_action)
      end

      it "redirects to the pending_action" do
        pending_action = PendingAction.create! valid_attributes
        put :update, {:id => pending_action.to_param, :pending_action => valid_attributes}, valid_session
        response.should redirect_to(pending_action)
      end
    end

    describe "with invalid params" do
      it "assigns the pending_action as @pending_action" do
        pending_action = PendingAction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PendingAction.any_instance.stub(:save).and_return(false)
        put :update, {:id => pending_action.to_param, :pending_action => {  }}, valid_session
        assigns(:pending_action).should eq(pending_action)
      end

      it "re-renders the 'edit' template" do
        pending_action = PendingAction.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PendingAction.any_instance.stub(:save).and_return(false)
        put :update, {:id => pending_action.to_param, :pending_action => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pending_action" do
      pending_action = PendingAction.create! valid_attributes
      expect {
        delete :destroy, {:id => pending_action.to_param}, valid_session
      }.to change(PendingAction, :count).by(-1)
    end

    it "redirects to the pending_actions list" do
      pending_action = PendingAction.create! valid_attributes
      delete :destroy, {:id => pending_action.to_param}, valid_session
      response.should redirect_to(pending_actions_url)
    end
  end

end
